const timezone_config = {
	GMT: { name: 'Greenwich Mean Time', tzutc: 'UTC', diff: '+00:00' },
	IBST: { name: 'International Business Standard Time', tzutc: 'UTC', diff: '+00:00' },
	WET: { name: 'Western European Time', tzutc: 'UTC', diff: '+00:00' },
	Z: { name: 'Zulu Time (Coordinated Universal Time)', tzutc: 'UTC', diff: '+00:00' },
	EGST: { name: 'Eastern Greenland Summer Time', tzutc: 'UTC+00', diff: '+00:00' },
	BST: { name: 'British Summer Time', tzutc: 'UTC+01', diff: '+01:00' },
	CET: { name: 'Central European Time', tzutc: 'UTC+01', diff: '+01:00' },
	DFT: {
		name: 'AIX specific equivalent of Central European Time',
		tzutc: 'UTC+01',
		diff: '+01:00'
	},
	IST: { name: 'Irish Standard Time', tzutc: 'UTC+01', diff: '+01:00' },
	MET: { name: 'Middle European Time Same zone as CET', tzutc: 'UTC+01', diff: '+01:00' },
	WAT: { name: 'West Africa Time', tzutc: 'UTC+01', diff: '+01:00' },
	WEDT: { name: 'Western European Daylight Time', tzutc: 'UTC+01', diff: '+01:00' },
	WEST: { name: 'Western European Summer Time', tzutc: 'UTC+01', diff: '+01:00' },
	CAT: { name: 'Central Africa Time', tzutc: 'UTC+02', diff: '+02:00' },
	CEDT: { name: 'Central European Daylight Time', tzutc: 'UTC+02', diff: '+02:00' },
	CEST: { name: 'Central European Summer Time', tzutc: 'UTC+02', diff: '+02:00' },
	EET: { name: 'Eastern European Time', tzutc: 'UTC+02', diff: '+02:00' },
	HAEC: {
		name: "Heure Avancée d'Europe Centrale francised name for CEST",
		tzutc: 'UTC+02',
		diff: '+02:00'
	},
	'IST Israel': { name: 'Israel Standard Time', tzutc: 'UTC+02', diff: '+02:00' },
	MEST: { name: 'Middle European Summer Time Same zone as CEST', tzutc: 'UTC+02', diff: '+02:00' },
	SAST: { name: 'South African Standard Time', tzutc: 'UTC+02', diff: '+02:00' },
	USZ1: { name: 'Kaliningrad Time', tzutc: 'UTC+02', diff: '+02:00' },
	WAST: { name: 'West Africa Summer Time', tzutc: 'UTC+02', diff: '+02:00' },
	'AST Arabia': { name: 'Arabia Standard Time', tzutc: 'UTC+03', diff: '+03:00' },
	EAT: { name: 'East Africa Time', tzutc: 'UTC+03', diff: '+03:00' },
	EEDT: { name: 'Eastern European Daylight Time', tzutc: 'UTC+03', diff: '+03:00' },
	EEST: { name: 'Eastern European Summer Time', tzutc: 'UTC+03', diff: '+03:00' },
	FET: { name: 'Further-eastern European Time', tzutc: 'UTC+03', diff: '+03:00' },
	IDT: { name: 'Israel Daylight Time', tzutc: 'UTC+03', diff: '+03:00' },
	IOT: { name: 'Indian Ocean Time', tzutc: 'UTC+03', diff: '+03:00' },
	MSK: { name: 'Moscow Time', tzutc: 'UTC+03', diff: '+03:00' },
	SYOT: { name: 'Showa Station Time', tzutc: 'UTC+03', diff: '+03:00' },
	IRST: { name: 'Iran Standard Time', tzutc: 'UTC+03:30', diff: '+03:30' },
	'AMT Armenia': { name: 'Armenia Time', tzutc: 'UTC+04', diff: '+04:00' },
	AZT: { name: 'Azerbaijan Time', tzutc: 'UTC+04', diff: '+04:00' },
	GET: { name: 'Georgia Standard Time', tzutc: 'UTC+04', diff: '+04:00' },
	'GST Gulf': { name: 'Gulf Standard Time', tzutc: 'UTC+04', diff: '+04:00' },
	MUT: { name: 'Mauritius Time', tzutc: 'UTC+04', diff: '+04:00' },
	RET: { name: 'Réunion Time', tzutc: 'UTC+04', diff: '+04:00' },
	SAMT: { name: 'Samara Time', tzutc: 'UTC+04', diff: '+04:00' },
	SCT: { name: 'Seychelles Time', tzutc: 'UTC+04', diff: '+04:00' },
	VOLT: { name: 'Volgograd Time', tzutc: 'UTC+04', diff: '+04:00' },
	AFT: { name: 'Afghanistan Time', tzutc: 'UTC+04:30', diff: '+04:30' },
	IRDT: { name: 'Iran Daylight Time', tzutc: 'UTC+04:30', diff: '+04:30' },
	HMT: { name: 'Heard and McDonald Islands Time', tzutc: 'UTC+05', diff: '+05:00' },
	MAWT: { name: 'Mawson Station Time', tzutc: 'UTC+05', diff: '+05:00' },
	MVT: { name: 'Maldives Time', tzutc: 'UTC+05', diff: '+05:00' },
	ORAT: { name: 'Oral Time', tzutc: 'UTC+05', diff: '+05:00' },
	PKT: { name: 'Pakistan Standard Time', tzutc: 'UTC+05', diff: '+05:00' },
	TFT: { name: 'Indian/Kerguelen', tzutc: 'UTC+05', diff: '+05:00' },
	TJT: { name: 'Tajikistan Time', tzutc: 'UTC+05', diff: '+05:00' },
	TMT: { name: 'Turkmenistan Time', tzutc: 'UTC+05', diff: '+05:00' },
	UZT: { name: 'Uzbekistan Time', tzutc: 'UTC+05', diff: '+05:00' },
	YEKT: { name: 'Yekaterinburg Time', tzutc: 'UTC+05', diff: '+05:00' },
	'IST Indian': { name: 'Indian Standard Time', tzutc: 'UTC+05:30', diff: '+05:30' },
	SLST: { name: 'Sri Lanka Standard Time', tzutc: 'UTC+05:30', diff: '+05:30' },
	NPT: { name: 'Nepal Time', tzutc: 'UTC+05:45', diff: '+05:45' },
	'BDT Bangladesh': { name: 'Bangladesh Daylight Time', tzutc: 'UTC+06', diff: '+06:00' },
	BIOT: { name: 'British Indian Ocean Time', tzutc: 'UTC+06', diff: '+06:00' },
	'BST Bangladesh': { name: 'Bangladesh Standard Time', tzutc: 'UTC+06', diff: '+06:00' },
	BTT: { name: 'Bhutan Time', tzutc: 'UTC+06', diff: '+06:00' },
	KGT: { name: 'Kyrgyzstan time', tzutc: 'UTC+06', diff: '+06:00' },
	OMST: { name: 'Omsk Time', tzutc: 'UTC+06', diff: '+06:00' },
	VOST: { name: 'Vostok Station Time', tzutc: 'UTC+06', diff: '+06:00' },
	CCT: { name: 'Cocos Islands Time', tzutc: 'UTC+06:30', diff: '+06:30' },
	MMT: { name: 'Myanmar Time', tzutc: 'UTC+06:30', diff: '+06:30' },
	'MST Myanmar': { name: 'Myanmar Standard Time', tzutc: 'UTC+06:30', diff: '+06:30' },
	CXT: { name: 'Christmas Island Time', tzutc: 'UTC+07', diff: '+07:00' },
	DAVT: { name: 'Davis Time', tzutc: 'UTC+07', diff: '+07:00' },
	HOVT: { name: 'Khovd Time', tzutc: 'UTC+07', diff: '+07:00' },
	ICT: { name: 'Indochina Time', tzutc: 'UTC+07', diff: '+07:00' },
	KRAT: { name: 'Krasnoyarsk Time', tzutc: 'UTC+07', diff: '+07:00' },
	THA: { name: 'Thailand Standard Time', tzutc: 'UTC+07', diff: '+07:00' },
	WIT: { name: 'Western Indonesian Time', tzutc: 'UTC+07', diff: '+07:00' },
	ACT: { name: 'ASEAN Common Time', tzutc: 'UTC+08', diff: '+08:00' },
	AWST: { name: 'Australian Western Standard Time', tzutc: 'UTC+08', diff: '+08:00' },
	BDT: { name: 'Brunei Time', tzutc: 'UTC+08', diff: '+08:00' },
	CHOT: { name: 'Choibalsan', tzutc: 'UTC+08', diff: '+08:00' },
	CIT: { name: 'Central Indonesia Time', tzutc: 'UTC+08', diff: '+08:00' },
	'CST China': { name: 'China Standard Time', tzutc: 'UTC+08', diff: '+08:00' },
	CT: { name: 'China time', tzutc: 'UTC+08', diff: '+08:00' },
	HKT: { name: 'Hong Kong Time', tzutc: 'UTC+08', diff: '+08:00' },
	IRKT: { name: 'Irkutsk Time', tzutc: 'UTC+08', diff: '+08:00' },
	'MST Malaysia': { name: 'Malaysia Standard Time', tzutc: 'UTC+08', diff: '+08:00' },
	MYT: { name: 'Malaysia Time', tzutc: 'UTC+08', diff: '+08:00' },
	'PST Philippine': { name: 'Philippine Standard Time', tzutc: 'UTC+08', diff: '+08:00' },
	SGT: { name: 'Singapore Time', tzutc: 'UTC+08', diff: '+08:00' },
	SST: { name: 'Singapore Standard Time', tzutc: 'UTC+08', diff: '+08:00' },
	ULAT: { name: 'Ulaanbaatar Time', tzutc: 'UTC+08', diff: '+08:00' },
	WST: { name: 'Western Standard Time', tzutc: 'UTC+08', diff: '+08:00' },
	CWST: { name: 'Central Western Standard Time (Australia)', tzutc: 'UTC+08:45', diff: '+08:45' },
	AWDT: { name: 'Australian Western Daylight Time', tzutc: 'UTC+09', diff: '+09:00' },
	EIT: { name: 'Eastern Indonesian Time', tzutc: 'UTC+09', diff: '+09:00' },
	JST: { name: 'Japan Standard Time', tzutc: 'UTC+09', diff: '+09:00' },
	KST: { name: 'Korea Standard Time', tzutc: 'UTC+09', diff: '+09:00' },
	TLT: { name: 'Timor Leste Time', tzutc: 'UTC+09', diff: '+09:00' },
	YAKT: { name: 'Yakutsk Time', tzutc: 'UTC+09', diff: '+09:00' },
	ACST: { name: 'Australian Central Standard Time', tzutc: 'UTC+09:30', diff: '+09:30' },
	'CST Australia Central': {
		name: 'Central Standard Time (Australia)',
		tzutc: 'UTC+09:30',
		diff: '+09:30'
	},
	AEST: { name: 'Australian Eastern Standard Time', tzutc: 'UTC+10', diff: '+10:00' },
	ChST: { name: 'Chamorro Standard Time', tzutc: 'UTC+10', diff: '+10:00' },
	CHUT: { name: 'Chuuk Time', tzutc: 'UTC+10', diff: '+10:00' },
	DDUT: { name: "Dumont d'Urville Time", tzutc: 'UTC+10', diff: '+10:00' },
	'EST Australia': { name: 'Eastern Standard Time (Australia)', tzutc: 'UTC+10', diff: '+10:00' },
	PGT: { name: 'Papua New Guinea Time', tzutc: 'UTC+10', diff: '+10:00' },
	VLAT: { name: 'Vladivostok Time', tzutc: 'UTC+10', diff: '+10:00' },
	ACDT: { name: 'Australian Central Daylight Savings Time', tzutc: 'UTC+10:30', diff: '+10:30' },
	'CST Australia Central Summer': {
		name: 'Central Summer Time (Australia)',
		tzutc: 'UTC+10:30',
		diff: '+10:30'
	},
	LHST: { name: 'Lord Howe Standard Time', tzutc: 'UTC+10:30', diff: '+10:30' },
	AEDT: { name: 'Australian Eastern Daylight Savings Time', tzutc: 'UTC+11', diff: '+11:00' },
	'BST Bougainville': { name: 'Bougainville Standard Time', tzutc: 'UTC+11', diff: '+11:00' },
	KOST: { name: 'Kosrae Time', tzutc: 'UTC+11', diff: '+11:00' },
	'LHST Lord Howe Summer': { name: 'Lord Howe Summer Time', tzutc: 'UTC+11', diff: '+11:00' },
	MIST: { name: 'Macquarie Island Station Time', tzutc: 'UTC+11', diff: '+11:00' },
	NCT: { name: 'New Caledonia Time', tzutc: 'UTC+11', diff: '+11:00' },
	PONT: { name: 'Pohnpei Standard Time', tzutc: 'UTC+11', diff: '+11:00' },
	SAKT: { name: 'Sakhalin Island time', tzutc: 'UTC+11', diff: '+11:00' },
	SBT: { name: 'Solomon Islands Time', tzutc: 'UTC+11', diff: '+11:00' },
	SRET: { name: 'Srednekolymsk Time', tzutc: 'UTC+11', diff: '+11:00' },
	VUT: { name: 'Vanuatu Time', tzutc: 'UTC+11', diff: '+11:00' },
	NFT: { name: 'Norfolk Time', tzutc: 'UTC+11:00', diff: '+11:00' },
	FJT: { name: 'Fiji Time', tzutc: 'UTC+12', diff: '+12:00' },
	GILT: { name: 'Gilbert Island Time', tzutc: 'UTC+12', diff: '+12:00' },
	MAGT: { name: 'Magadan Time', tzutc: 'UTC+12', diff: '+12:00' },
	MHT: { name: 'Marshall Islands', tzutc: 'UTC+12', diff: '+12:00' },
	NZST: { name: 'New Zealand Standard Time', tzutc: 'UTC+12', diff: '+12:00' },
	PETT: { name: 'Kamchatka Time', tzutc: 'UTC+12', diff: '+12:00' },
	TVT: { name: 'Tuvalu Time', tzutc: 'UTC+12', diff: '+12:00' },
	WAKT: { name: 'Wake Island Time', tzutc: 'UTC+12', diff: '+12:00' },
	CHAST: { name: 'Chatham Standard Time', tzutc: 'UTC+12:45', diff: '+12:45' },
	NZDT: { name: 'New Zealand Daylight Time', tzutc: 'UTC+13', diff: '+13:00' },
	PHOT: { name: 'Phoenix Island Time', tzutc: 'UTC+13', diff: '+13:00' },
	TKT: { name: 'Tokelau Time', tzutc: 'UTC+13', diff: '+13:00' },
	TOT: { name: 'Tonga Time', tzutc: 'UTC+13', diff: '+13:00' },
	CHADT: { name: 'Chatham Daylight Time', tzutc: 'UTC+13:45', diff: '+13:45' },
	LINT: { name: 'Line Islands Time', tzutc: 'UTC+14', diff: '+14:00' },
	AZOST: { name: 'Azores Standard Time', tzutc: 'UTC-01', diff: '-01:00' },
	CVT: { name: 'Cape Verde Time', tzutc: 'UTC-01', diff: '-01:00' },
	EGT: { name: 'Eastern Greenland Time', tzutc: 'UTC-01', diff: '-01:00' },
	BRST: { name: 'Brasilia Summer Time', tzutc: 'UTC-02', diff: '-02:00' },
	FNT: { name: 'Fernando de Noronha Time', tzutc: 'UTC-02', diff: '-02:00' },
	GST: { name: 'South Georgia and the South Sandwich Islands', tzutc: 'UTC-02', diff: '-02:00' },
	PMDT: { name: 'Saint Pierre and Miquelon Daylight time', tzutc: 'UTC-02', diff: '-02:00' },
	UYST: { name: 'Uruguay Summer Time', tzutc: 'UTC-02', diff: '-02:00' },
	NDT: { name: 'Newfoundland Daylight Time', tzutc: 'UTC-02:30', diff: '-02:30' },
	ADT: { name: 'Atlantic Daylight Time', tzutc: 'UTC-03', diff: '-03:00' },
	AMST: { name: 'Amazon Summer Time (Brazil)', tzutc: 'UTC-03', diff: '-03:00' },
	ART: { name: 'Argentina Time', tzutc: 'UTC-03', diff: '-03:00' },
	BRT: { name: 'Brasilia Time', tzutc: 'UTC-03', diff: '-03:00' },
	CLST: { name: 'Chile Summer Time', tzutc: 'UTC-03', diff: '-03:00' },
	FKST: { name: 'Falkland Islands Standard Time', tzutc: 'UTC-03', diff: '-03:00' },
	'FKST Falkland Islands Summer': {
		name: 'Falkland Islands Summer Time',
		tzutc: 'UTC-03',
		diff: '-03:00'
	},
	GFT: { name: 'French Guiana Time', tzutc: 'UTC-03', diff: '-03:00' },
	PMST: { name: 'Saint Pierre and Miquelon Standard Time', tzutc: 'UTC-03', diff: '-03:00' },
	PYST: { name: 'Paraguay Summer Time (South America)', tzutc: 'UTC-03', diff: '-03:00' },
	ROTT: { name: 'Rothera Research Station Time', tzutc: 'UTC-03', diff: '-03:00' },
	SRT: { name: 'Suriname Time', tzutc: 'UTC-03', diff: '-03:00' },
	UYT: { name: 'Uruguay Standard Time', tzutc: 'UTC-03', diff: '-03:00' },
	NST: { name: 'Newfoundland Standard Time', tzutc: 'UTC-03:30', diff: '-03:30' },
	NT: { name: 'Newfoundland Time', tzutc: 'UTC-03:30', diff: '-03:30' },
	AMT: { name: 'Amazon Time (Brazil)', tzutc: 'UTC-04', diff: '-04:00' },
	AST: { name: 'Atlantic Standard Time', tzutc: 'UTC-04', diff: '-04:00' },
	BOT: { name: 'Bolivia Time', tzutc: 'UTC-04', diff: '-04:00' },
	'CDT Cuba': { name: 'Cuba Daylight Time', tzutc: 'UTC-04', diff: '-04:00' },
	CLT: { name: 'Chile Standard Time', tzutc: 'UTC-04', diff: '-04:00' },
	COST: { name: 'Colombia Summer Time', tzutc: 'UTC-04', diff: '-04:00' },
	ECT: { name: 'Eastern Caribbean Time', tzutc: 'UTC-04', diff: '-04:00' },
	EDT: { name: 'Eastern Daylight Time (North America)', tzutc: 'UTC-04', diff: '-04:00' },
	FKT: { name: 'Falkland Islands Time', tzutc: 'UTC-04', diff: '-04:00' },
	GYT: { name: 'Guyana Time', tzutc: 'UTC-04', diff: '-04:00' },
	PYT: { name: 'Paraguay Time (South America)', tzutc: 'UTC-04', diff: '-04:00' },
	VET: { name: 'Venezuelan Standard Time', tzutc: 'UTC-04:30', diff: '-04:30' },
	'ACT Acre': { name: 'Acre Time', tzutc: 'UTC-05', diff: '-05:00' },
	CDT: { name: 'Central Daylight Time (North America)', tzutc: 'UTC-05', diff: '-05:00' },
	COT: { name: 'Colombia Time', tzutc: 'UTC-05', diff: '-05:00' },
	'CST Cuba': { name: 'Cuba Standard Time', tzutc: 'UTC-05', diff: '-05:00' },
	EASST: { name: 'Easter Island Standard Summer Time', tzutc: 'UTC-05', diff: '-05:00' },
	'ECT Ecuador': { name: 'Ecuador Time', tzutc: 'UTC-05', diff: '-05:00' },
	EST: { name: 'Eastern Standard Time (North America)', tzutc: 'UTC-05', diff: '-05:00' },
	PET: { name: 'Peru Time', tzutc: 'UTC-05', diff: '-05:00' },
	CST: { name: 'Central Standard Time (North America)', tzutc: 'UTC-06', diff: '-06:00' },
	EAST: { name: 'Easter Island Standard Time', tzutc: 'UTC-06', diff: '-06:00' },
	GALT: { name: 'Galapagos Time', tzutc: 'UTC-06', diff: '-06:00' },
	MDT: { name: 'Mountain Daylight Time (North America)', tzutc: 'UTC-06', diff: '-06:00' },
	MST: { name: 'Mountain Standard Time (North America)', tzutc: 'UTC-07', diff: '-07:00' },
	PDT: { name: 'Pacific Daylight Time (North America)', tzutc: 'UTC-07', diff: '-07:00' },
	AKDT: { name: 'Alaska Daylight Time', tzutc: 'UTC-08', diff: '-08:00' },
	CIST: { name: 'Clipperton Island Standard Time', tzutc: 'UTC-08', diff: '-08:00' },
	PST: { name: 'Pacific Standard Time (North America)', tzutc: 'UTC-08', diff: '-08:00' },
	AKST: { name: 'Alaska Standard Time', tzutc: 'UTC-09', diff: '-09:00' },
	GAMT: { name: 'Gambier Islands', tzutc: 'UTC-09', diff: '-09:00' },
	GIT: { name: 'Gambier Island Time', tzutc: 'UTC-09', diff: '-09:00' },
	HADT: { name: 'Hawaii-Aleutian Daylight Time', tzutc: 'UTC-09', diff: '-09:00' },
	MART: { name: 'Marquesas Islands Time', tzutc: 'UTC-09:30', diff: '-09:30' },
	MIT: { name: 'Marquesas Islands Time', tzutc: 'UTC-09:30', diff: '-09:30' },
	CKT: { name: 'Cook Island Time', tzutc: 'UTC-10', diff: '-10:00' },
	HAST: { name: 'Hawaii-Aleutian Standard Time', tzutc: 'UTC-10', diff: '-10:00' },
	HST: { name: 'Hawaii Standard Time', tzutc: 'UTC-10', diff: '-10:00' },
	TAHT: { name: 'Tahiti Time', tzutc: 'UTC-10', diff: '-10:00' },
	NUT: { name: 'Niue Time', tzutc: 'UTC-11', diff: '-11:00' },
	'SST Samoa': { name: 'Samoa Standard Time', tzutc: 'UTC-11', diff: '-11:00' },
	BIT: { name: 'Baker Island Time', tzutc: 'UTC-12', diff: '-12:00' }
};
const TimeZone = {
	getTimeZoneArray: function () {
		let ret = [];
		for (let [key, value] of Object.entries(timezone_config)) {
			value = { key: key, ...value };
			ret.push(value);
		}
		return ret;
	},
	getDiff: function (tzcode) {
		let def = timezone_config[tzcode];
		if (def) {
			return def.diff;
		} else {
			return '+00:00';
		}
	}
};

export default TimeZone;
